id: 915e3aeebc844a21b5973c18c5ab217c
initial_creation_type: ocr
source_metadata:
  volumes:
    f2712b116a0e4928bc339162c4088843:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
